# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='login')),
                ('senha', models.CharField(max_length=250, verbose_name='senha')),
                ('cep', models.CharField(max_length=250, verbose_name='cep')),
                ('endereco', models.CharField(max_length=250, verbose_name='endereco')),
                ('numero', models.CharField(max_length=250, verbose_name='numero')),
                ('bairro', models.CharField(max_length=250, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=250, verbose_name='cidade')),
                ('estado', models.CharField(max_length=250, verbose_name='estado')),
            ],
        ),
    ]
