# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=250, unique=True, verbose_name='email'),
        ),
    ]
