# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-08 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210507_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True, verbose_name='nome')),
                ('estoque', models.DecimalField(blank=True, decimal_places=10, max_digits=20, verbose_name='estoque')),
                ('preco', models.DecimalField(blank=True, decimal_places=10, max_digits=20, verbose_name='preco')),
            ],
        ),
    ]
